# Generated by Django 5.0.14 on 2025-10-05 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_catalog_extras'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
